### ISSUE TITLE
Add option to use different name for generated struct

### ISSUE THREAD

**Issue by prusnak** [japaric/svd2rust#57]
See the followings script for example:

https://github.com/brandonedens/stm32l4x6-memory-map/blob/master/gen-peripherals.sh

It uses `sed` to rename struct name from `I2c1` to `I2c` if the definition could be shared among more peripherals of the same type.

It would be nice to have option directly in svd2rust so one does not need to use sed.

For example `svd2rust -i $svd i2c1:I2c ` or `svd2rust -i $svd i2c1 -n I2c`

**Comment by japaric** [comment]
Today, we (a) generate code for the whole device instead of per peripheral, (b) generate one type per peripheral instance and (c) the name of that type matches the peripheral instance (`I2c1`, `I2c2`, etc.) so it's no longer necessary to (a) use a shell script to build a device crate or (b) sed the output.

I feel that this no longer required so I'm going to close this issue. If you feel otherwise, feel free to open a new issue with updated rationale.

**Comment by prusnak** [comment]
Great! Thanks!
